### ISSUE TITLE
Some calculations giving odd currency amounts

### ISSUE THREAD

**Issue by leecollings** [jpederson/Accrue.js#14]
Some of my selections are offering stupid currency amounts that just wouldn't happen in the real world. Is there any way to apply a simple number rounding?

For example, I have a product where the base price is £380. I'm adding 8% onto the monthly amounts, and my monthly options are 6, 10 and 12 months.

Using the above base price, when selecting these I am provided with the following monthly payments:

6 months - £68.39,999,999,999,999 per month
10 months - £41.04 per month
12 months - £34.199,999,999,999,996 per month

There are also some amounts that omit the final 0 from the pence value ie. £50.3
Is there a way to format these into a 'currency' format, like you would do on a spreadsheet?

**Comment by leecollings** [comment]
Hello? Can you please assist me with this issue?

**Comment by jpederson** [comment]
What function are you using to get these amounts? If I use the built-in `$.loanInfo` function, it returns both a formatted value and a full value (before rounding), but I never receive the unrounded values when I'm just calling `$(selector).accrue()` on a div. If you are using that `$.loanInfo` function and you're pulling the value into a variable, a simple `varname.toFixed(2)` will spit it out with only 2 decimal places - or you can use something like `Math.ceil(varname)` to round up or `Math.floor(varname)` to round down.

I need more information about where these numbers are coming from for you. The `$.loanInfo` function returns both rounded and unrounded numbers so that you can use the unrounded numbers in other calculations and then do your rounding - so it's sort of designed that way. Can you should a jsfiddle of how you're getting these numbers?

- James

**Comment by leecollings** [comment]
This is the initialisation JS code I'm using, if this helps?

```
$('.click').click(function(){
        if ($('#finance-calculator .amount :selected').text() == "Select a procedure...") { return false; }
        //prepopulate the input fields with the chosen options
        var financeamount = $('#finance-calculator .amount').val();
        var baseprice = financeamount / 1.08;
        var financedeposit = parseInt(financeamount) * 0.00;
        var financepayable = parseInt(financeamount) + financedeposit;
        var financeterm = $('#finance-calculator .active input[name=term]').val();
        var financemonthly = financepayable / parseInt(financeterm);
        
        $('#finance-calculator .results').empty();
                        
        $('#finance-calculator .finance_price').val(financeamount);
        $('#finance-calculator .finance_description').val($('#finance-calculator .amount :selected').text());
        $('#finance-calculator .finance_code').val('ONIF' + financeterm);
        
        if (financeterm !== "0") {
            $('#finance-calculator .results').append("<p class='halfmargin'>Prices could start from as little as</p><p class='outline'>£" + numberWithCommas(financemonthly) + " per month*</p>");
            $('#finance-calculator .finance_button').show();
        } else {
            $('#finance-calculator .results').append("<p>Prices start from <strong>£" + numberWithCommas(financeamount) + "</strong></p>");
            $('#finance-calculator .finance_button').hide();
        }
                
	$('#finance-calculator .calculator').toggleClass('flip');
    });
```

**Comment by jpederson** [comment]
See my last comment about how to round numbers in JS. Based on the code you provided, you're not even using my jQuery plugin, so this question would be more appropriately asked on something like StackOverflow.. I'm not here to support every persons Javascript math lol.. I do try, but this issues area is for my plugin specifically - and that code doesn't call `.accrue()` or the provided `$.loanInfo()` function.

**Comment by leecollings** [comment]
I definitely was using the accrue plugin.. maybe I took the workings from it and dumped it all in that code I gave above, I can't remember to be honest.

Well, sorry for wasting your time, but you did at least help me in realise how to round numbers, that's exactly what I was looking for. Working perfectly now.
