### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by davemcg3** [jpederson/Accrue.js#25]
Hey, this is a great plugin.  Thanks for your hard work on it.  In your LICENSE file you state that this is licensed under an MIT license but under the actual accrue.js file where all the magic happens you specify both MIT and GPL licenses.  Those licenses have different terms, particularly whether this can be used in commercial works or not.  So, specifically, are you licensing this software to be used in a commercial website without open sourcing the commercial website?  MIT license would allow that use case, GPL license would not.

**Comment by jpederson** [comment]
I've been contemplating a switch to a WTFPL or the like, but please trust that I want you and anyone else to be able to use this for anything you like, commercial or otherwise. I'll update the license accordingly, but please consider this my permission to use commercially without open sourcing anything.

**Comment by davemcg3** [comment]
I wasn't familiar with the WTFPL so I had to look it up and it's for sure my kind of license.  I've been playing with accrue.js on my dev server and it's exactly what I need, and now I don't have to write it myself.  Cheers mate!

**Comment by jpederson** [comment]
Have fun, and thanks for clarifying!
