### ISSUE TITLE
Show date/month/year in table

### ISSUE THREAD

**Issue by ghost** [jpederson/Accrue.js#31]
Nice plugin, but need in **amortization** in table show date/month/year column.
How can do it?
Thx.

![screenshot_3](https://cloud.githubusercontent.com/assets/7046596/22070263/cbe0e5ac-ddb4-11e6-8bd2-226088eff607.png)

**Comment by jpederson** [comment]
For this, I'd suggest forking the repo and customizing your own copy. This tool is mostly used for example amortization schedules - I included 'payment number' so that the tool could accommodate monthly, weekly, biweekly, or even daily payments (if required).

I'd suggest using javascript's date object:
```js
var now = new Date();
current = new Date(now.getFullYear(), now.getMonth()+(i+1), 1);
```

The variable `i` is used to contain the current item in the for loop on line 351 of jquery.accrue.js.
