### ISSUE TITLE
Replace input field with radio select for Term

### ISSUE THREAD

**Issue by leecollings** [jpederson/Accrue.js#8]
Is it possible to switch the 'Terms' input field for a radio selection, so I can pre-set the terms available, and have the user click which one, and automatically update?

**Comment by jpederson** [comment]
Yes, you can manually create your own fields as needed - check out the wiki section https://github.com/jpederson/Accrue.js/wiki/Customizing-Fields for more information on that - it has samples of how to add any of the fields, and have Accrue detect them.

**Comment by jpederson** [comment]
I should specify - I'm not sure if radio inputs will work, but you can certainly use a select list to have preset rates that the user can select.

**Comment by leecollings** [comment]
I already use select lists, it's specifically radio selects that is like to
use.

Why would there be a difference?

On Friday, 5 June 2015, James Pederson <notifications@github.com> wrote:

> I should specify - I'm not sure if radio inputs will work, but you can
> certainly use a select list to have preset rates that the user can select.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jpederson/Accrue.js/issues/8#issuecomment-109394867>.
>


-- 
Regards,

*Lee*

**Comment by jpederson** [comment]
They're a different kind of input, and hence the JS needs to handle them differently - it can't just select a radio input, because there are several by the same name, an only one will be checked, so I'd have to build in a special case for it, and haven't yet.

If you'd like to take a stab at adding it, feel free to fork and submit a pull request, I'm happy to include the change if you make it, but as I said, my schedule is a bit hectic for the next month or so, and won't allow me the time to make the adjustments myself for a while.

- James

**Comment by leecollings** [comment]
Hi James,

I'm coming back to this, to see if I can get it working.. and it doesn't seem that simple. I'm wondering if you'd had a look at it all?
